"""add relation

Revision ID: 736ae5af9030
Revises: 85bb2a52723c
Create Date: 2019-03-14 18:32:49.907873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736ae5af9030'
down_revision = '85bb2a52723c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('art_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['art_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation')
    # ### end Alembic commands ###
