"""article and category table mod

Revision ID: 9becfedd7137
Revises: d466d7f96360
Create Date: 2019-03-12 17:23:58.751374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9becfedd7137'
down_revision = 'd466d7f96360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_article_is_topping'), 'article', ['is_topping'], unique=False)
    op.create_index(op.f('ix_article_status'), 'article', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_status'), table_name='article')
    op.drop_index(op.f('ix_article_is_topping'), table_name='article')
    # ### end Alembic commands ###
