"""empty message

Revision ID: a6f227f825d0
Revises: a2ac1402a5cb
Create Date: 2019-03-14 20:56:23.099265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f227f825d0'
down_revision = 'a2ac1402a5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relation', sa.Column('is_deleted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relation', 'is_deleted')
    # ### end Alembic commands ###
